//
// automatically generated by spin2cpp v1.03 on Wed Sep 04 18:41:35 2013
// ..\spin2cpp.exe --ccode talk.spin 
//

#ifndef talk_Class_Defined__
#define talk_Class_Defined__

#include <stdint.h>
#include "VocalTract.h"

#define Zero (255)
#define Aaz (0)
#define Gaz (1)
#define Gp (2)
#define Vp (3)
#define Vr (4)
#define F1 (5)
#define F2 (6)
#define F3 (7)
#define F4 (8)
#define Naz (9)
#define Nf (10)
#define Faz (11)
#define Ff (12)
#define Aa (13)
#define Ga (14)
#define Na (15)
#define Fa (16)
#define Gps (17)
#define Qt (18)

typedef struct talk {
  uint16_t	Glide, Base_freq, Gain, Dilate;
  uint8_t	Vt[18], Vtp[18], Cbuf[300], Speaker[10];
  uint8_t	Vocal_cog, Aspirate, Initial_k, Initial_g, Whisper, Volume;
  char dummy__;
} talk;

  int32_t	talk_Start(int32_t Pin);
  int32_t	talk_Stop(void);
  int32_t	talk_Set_speaker(int32_t Spkr, int32_t Base);
  // the following are modified
  int32_t	talk_Spell(const char *Ptr);
  int32_t	talk_Say(const char *Ptr);
#endif
