//
// automatically generated by spin2cpp v1.03 on Wed Sep 04 18:41:35 2013
// ..\spin2cpp.exe --ccode talk.spin 
//

#include <stdlib.h>
#include <propeller.h>
#include <string.h> // we use "strncpy"
#include "talk.h"

#ifdef __GNUC__
#define INLINE__ static inline
#define PostEffect__(X, Y) __extension__({ int32_t tmp__ = (X); (X) = (Y); tmp__; })
#else
#define INLINE__ static
static int32_t tmp__;
#define PostEffect__(X, Y) (tmp__ = (X), (X) = (Y), tmp__)
#define waitcnt(n) _waitcnt(n)
#define locknew() _locknew()
#define lockret(i) _lockret(i)
#define lockset(i) _lockset(i)
#define lockclr(i) _lockclr(i)
#define coginit(id, code, par) _coginit((unsigned)(par)>>2, (unsigned)(code)>>2, id)
#define cognew(code, par) coginit(0x8, (code), (par))
#define cogstop(i) _cogstop(i)
#endif

INLINE__ int32_t Min__(int32_t a, int32_t b) { return a < b ? a : b; }
INLINE__ int32_t Max__(int32_t a, int32_t b) { return a > b ? a : b; }
#include <setjmp.h>
typedef struct { jmp_buf jmp; int32_t val; } AbortHook__;
AbortHook__ *abortChain__ __attribute__((common));

INLINE__ int32_t Shr__(uint32_t a, uint32_t b) { return (a>>b); }
INLINE__ int32_t Between__(int32_t x, int32_t a, int32_t b){ if (a <= b) return x >= a && x <= b; return x >= b && x <= a; }

static  int32_t	talk_Formant(int32_t Sf1, int32_t Sf2, int32_t Sf3, int32_t Sf4);
static  int32_t	talk_Set(int32_t Fmt, int32_t Ptr, int32_t Pre, int32_t Time, int32_t Post);
static talk thisobj;
static uint8_t dat[] = {
  0x80, 0x00, 0x8c, 0x00, 0x98, 0x00, 0xa6, 0x00, 0xb5, 0x00, 0xc5, 0x00, 0xd7, 0x00, 0xeb, 0x00, 
  0x00, 0x01, 0x17, 0x01, 0x30, 0x01, 0x4c, 0x01, 0x6a, 0x01, 0x8b, 0x01, 0xaf, 0x01, 0xd6, 0x01, 
  0x00, 0x02, 
};
int32_t talk_Start(int32_t Pin)
{
  talk_Stop();
  thisobj.Vocal_cog = VocalTract_Start((int32_t)(&thisobj.Vt), Pin, (-1), (-1));
  memset( (void *)&thisobj.Speaker, 100, 1*(10));
  thisobj.Base_freq = 100;
  return 0;
}

int32_t talk_Stop(void)
{
  if (thisobj.Vocal_cog) {
    cogstop((thisobj.Vocal_cog - 1));
    thisobj.Vocal_cog = 0;
  }
  return 0;
}

int32_t talk_Set_speaker(int32_t Spkr, int32_t Base)
{
  thisobj.Speaker[(Min__((Max__(Spkr, 0)), 9))] = Base;
  return 0;
}

int32_t talk_Spell(const char *Ptr)
{
  const unsigned short syllable_max = 40;
  int32_t Char;
  char S[syllable_max];
  while ((Char = ((uint8_t *)(Ptr++))[0])) {
    if ((Char >= 'A') && (Char <= 'Z')) {
      talk_Say("k\'apitul");
      Char += 32;
    }
    if (Char == ' ') {
      strncpy(S, "spays", syllable_max);
    } else if (Char == 'a') {
      strncpy(S, "ay", syllable_max);
    } else if (Char == 'b') {
      strncpy(S, "bee", syllable_max);
    } else if (Char == 'c') {
      strncpy(S, "see", syllable_max);
    } else if (Char == 'd') {
      strncpy(S, "dee", syllable_max);
    } else if (Char == 'e') {
      strncpy(S, "ee", syllable_max);
    } else if (Char == 'f') {
      strncpy(S, "ef", syllable_max);
    } else if (Char == 'g') {
      strncpy(S, "jee", syllable_max);
    } else if (Char == 'h') {
      strncpy(S, "aych", syllable_max);
    } else if (Char == 'i') {
      strncpy(S, "ae", syllable_max);
    } else if (Char == 'j') {
      strncpy(S, "jay", syllable_max);
    } else if (Char == 'k') {
      strncpy(S, "kay", syllable_max);
    } else if (Char == 'l') {
      strncpy(S, "el", syllable_max);
    } else if (Char == 'm') {
      strncpy(S, "em~", syllable_max);
    } else if (Char == 'n') {
      strncpy(S, "en~", syllable_max);
    } else if (Char == 'o') {
      strncpy(S, "oa", syllable_max);
    } else if (Char == 'p') {
      strncpy(S, "pee", syllable_max);
    } else if (Char == 'q') {
      strncpy(S, "kew", syllable_max);
    } else if (Char == 'r') {
      strncpy(S, "ar", syllable_max);
    } else if (Char == 's') {
      strncpy(S, "ess", syllable_max);
    } else if (Char == 't') {
      strncpy(S, "tee", syllable_max);
    } else if (Char == 'u') {
      strncpy(S, "yoo", syllable_max);
    } else if (Char == 'v') {
      strncpy(S, "vee", syllable_max);
    } else if (Char == 'w') {
      strncpy(S, "d\'ubulyoo", syllable_max);
    } else if (Char == 'x') {
      strncpy(S, "eks", syllable_max);
    } else if (Char == 'y') {
      strncpy(S, "wae", syllable_max);
    } else if (Char == 'z') {
      strncpy(S, "zee", syllable_max);
    } else if (Char == '0') {
      strncpy(S, "z\'eeroa", syllable_max);
    } else if (Char == '1') {
      strncpy(S, "wun~", syllable_max);
    } else if (Char == '2') {
      strncpy(S, "too", syllable_max);
    } else if (Char == '3') {
      strncpy(S, "three", syllable_max);
    } else if (Char == '4') {
      strncpy(S, "for", syllable_max);
    } else if (Char == '5') {
      strncpy(S, "faev", syllable_max);
    } else if (Char == '6') {
      strncpy(S, "siks", syllable_max);
    } else if (Char == '7') {
      strncpy(S, "s\'even~", syllable_max);
    } else if (Char == '8') {
      strncpy(S, "ayt", syllable_max);
    } else if (Char == '9') {
      strncpy(S, "naen~", syllable_max);
    } else if (Char == '.') {
      strncpy(S, "p\'eereeud", syllable_max);
    } else if (Char == ',') {
      strncpy(S, "k\'omu", syllable_max);
    } else if (Char == ':') {
      strncpy(S, "k\'oalun~", syllable_max);
    } else if (Char == '?') {
      strncpy(S, "kw\'estshun mark~", syllable_max);
    } else if (Char == '!') {
      strncpy(S, "\'eksklam\'ayshun point", syllable_max);
    } else if (Char == ';') {
      strncpy(S, "s\'emaekoalun~", syllable_max);
    } else if (Char == '\'') {
      strncpy(S, "uhp\'ostrufee", syllable_max);
    } else if (Char == '@') {
      strncpy(S, "at", syllable_max);
    } else if (Char == '#') {
      strncpy(S, "n\'umber", syllable_max);
    } else if (Char == '$') {
      strncpy(S, "d\'olur saen", syllable_max);
    } else if (Char == '%') {
      strncpy(S, "pers\'ent", syllable_max);
    } else if (Char == '^') {
      strncpy(S, "k\'a rut", syllable_max);
    } else if (Char == '&') {
      strncpy(S, "\'ampersand", syllable_max);
    } else if (Char == '*') {
      strncpy(S, "star", syllable_max);
    } else if (Char == '(') {
      strncpy(S, "left pur\'enthesis", syllable_max);
    } else if (Char == ')') {
      strncpy(S, "raet pur\'enthesis", syllable_max);
    } else if (Char == '-') {
      strncpy(S, "haefun", syllable_max);
    } else if (Char == '_') {
      strncpy(S, "\'underskor", syllable_max);
    } else if (Char == '+') {
      strncpy(S, "plus", syllable_max);
    } else if (Char == '=') {
      strncpy(S, "\'eekwol saen~", syllable_max);
    } else if (1) {
      strncpy(S, "\'unoan k\'a racter", syllable_max);
    }
    talk_Say(S);
    talk_Say(";");
  }
  return 0;
}

int32_t talk_Say(const char *Ptr)
{
  int32_t	This, Nxt, Octave;
  int32_t result = 0;
  if (thisobj.Vocal_cog == 0) {
    return result;
  }
  thisobj.Vt[Gp] = (thisobj.Vt[Gps] = thisobj.Base_freq);
  thisobj.Initial_k = (thisobj.Initial_g = (thisobj.Aspirate = (thisobj.Whisper = 0)));
  thisobj.Volume = 6;
  thisobj.Dilate = 100;
  talk_Set(talk_Formant(650, 990, 2530, 3480), (int32_t)"\022", 0, 10, 0);
  while ((This = ((uint8_t *)(Ptr++))[0])) {
    if (This == '_') {
      thisobj.Vt[Gp] = (thisobj.Vt[Gps] = thisobj.Base_freq);
    } else if (This == '/') {
      thisobj.Vt[Gps] = (thisobj.Vt[Gps] + 4);
    } else if (This == '\\') {
      thisobj.Vt[Gps] = (thisobj.Vt[Gps] - 4);
    } else if (This == '[') {
      thisobj.Vt[Gps] = (thisobj.Vt[Gp] = (thisobj.Vt[Gp] + 4));
    } else if (This == ']') {
      thisobj.Vt[Gps] = (thisobj.Vt[Gp] = (thisobj.Vt[Gp] - 4));
    } else if (This == '\'') {
      thisobj.Vt[Gp] = (thisobj.Vt[Gp] + 4);
    } else if (This == ',') {
      talk_Set(0, (int32_t)"\022", 100, 200, 0);
    } else if (This == ';') {
      talk_Set(0, (int32_t)"\022", 100, 450, 0);
    } else if (This == '.') {
      talk_Set(0, (int32_t)"\022", 100, 750, 0);
    } else if (This == '|') {
      thisobj.Glide = 0;
    } else if (This == '(') {
      thisobj.Whisper = -1;
    } else if (This == ')') {
      thisobj.Whisper = 0;
    } else if (This == '%') {
      thisobj.Dilate = 0;
      while (((Nxt = ((uint8_t *)(Ptr++))[0]) >= '0') && (Nxt <= '9')) {
        thisobj.Dilate = (((thisobj.Dilate * 10) + Nxt) - '0');
      }
      (Ptr--);
      if (thisobj.Dilate) {
        thisobj.Dilate = (Min__((Max__(thisobj.Dilate, 25)), 1600));
      } else {
        thisobj.Dilate = 100;
      }
    } else if (This == '~') {
      talk_Set(talk_Formant(640, 1200, 2400, 3000), (int32_t)"\016\017", 10, 15, 10);
    } else if (This == '#' || This == '_' || Between__(This, 'A', 'G') || This == '+' || This == '-' || This == '=' || This == '<' || This == '>' || This == 'a' || This == 'e' || This == 'i' || This == 'o' || This == 'u' || This == 'd' || This == 't' || This == 's' || This == 'c' || This == 'k' || This == 'g' || This == 'z' || This == 'r') {
      Nxt = ((uint8_t *)(Ptr++))[0];
      if (This == '#') {
        if (Between__(Nxt, '0', '9')) {
          thisobj.Base_freq = thisobj.Speaker[(Nxt - '0')];
        } else if (1) {
          (Ptr--);
          thisobj.Base_freq = thisobj.Speaker[0];
        }
        thisobj.Vt[Gp] = (thisobj.Vt[Gps] = thisobj.Base_freq);
      } else if (Between__(This, 'A', 'G')) {
        if (Between__(Nxt, '1', '5')) {
          Octave = (Nxt - '0');
        } else if (1) {
          (Ptr--);
          Octave = ((thisobj.Vt[Gp] + 32) / 48);
        }
        thisobj.Vt[Gp] = (thisobj.Vt[Gps] = (Min__((((Octave - 1) * 48) + ((uint8_t *)(int32_t)"4<\020\030 $,")[(This - 'A')]), 255)));
      } else if (This == '+' || This == '-') {
        if (Between__(Nxt, '1', '9')) {
          thisobj.Vt[Gp] = (thisobj.Vt[Gp] + (((',' - This) * (Nxt - '0')) << 2));
        } else if (1) {
          (Ptr--);
          thisobj.Vt[Gp] = (thisobj.Vt[Gp] + ((',' - This) << 2));
        }
        thisobj.Vt[Gps] = thisobj.Vt[Gp];
      } else if (This == '=') {
        if (Between__(Nxt, '0', '9')) {
          thisobj.Volume = (Nxt - '0');
        } else if (1) {
          (Ptr--);
          thisobj.Volume = 6;
        }
      } else if (This == '<' || This == '>') {
        if (Between__(Nxt, '0', '9')) {
          thisobj.Volume = (Max__((Min__((thisobj.Volume + (('=' - This) * (Nxt - '0'))), 9)), 0));
        } else if (1) {
          (Ptr--);
          thisobj.Volume = (Max__((Min__(((thisobj.Volume + '=') - This), 9)), 0));
        }
      } else if (This == 'a') {
        if (Nxt == 'e') {
          talk_Set(talk_Formant(650, 990, 2530, 3480), 0, 10, 1, 300);
          talk_Set(talk_Formant(310, 2020, 2960, 3500), 0, 300, 50, 100);
        } else if (Nxt == 'l') {
          talk_Set(talk_Formant(660, 1700, 2400, 3900), 0, 200, 200, 100);
          talk_Set(talk_Formant(310, 1050, 2880, 3500), 0, 100, 200, 50);
        } else if (Nxt == 'i' || Nxt == 'y') {
          talk_Set(talk_Formant(660, 1700, 2400, 3900), 0, 200, 0, 150);
          talk_Set(talk_Formant(310, 2020, 2960, 3500), 0, 150, 200, 100);
        } else if (Nxt == 'r') {
          talk_Set(talk_Formant(650, 990, 2530, 3480), 0, 200, 100, 100);
          talk_Set(talk_Formant(470, 1120, 2430, 3400), 0, 100, 200, 100);
          talk_Set(talk_Formant(310, 1060, 1380, 3500), (int32_t)"\022", 100, 200, 200);
        } else if (Nxt == 'h') {
          talk_Set(talk_Formant(650, 990, 2530, 3480), 0, 200, 200, 100);
        } else if (1) {
          (Ptr--);
          talk_Set(talk_Formant(660, 1700, 2400, 3900), 0, 200, 200, 100);
        }
      } else if (This == 'e') {
        if (Nxt == 'e') {
          talk_Set(talk_Formant(310, 2020, 2960, 3500), 0, 100, 200, 100);
        } else if (Nxt == 'w') {
          talk_Set(talk_Formant(310, 2020, 2960, 3500), 0, 100, 0, 150);
          talk_Set(talk_Formant(300, 870, 2250, 3900), 0, 200, 100, 100);
        } else if (Nxt == 'r') {
          talk_Set(talk_Formant(470, 1120, 2430, 3400), 0, 100, 200, 100);
          talk_Set(talk_Formant(310, 1060, 1380, 3500), (int32_t)"\022", 100, 200, 200);
        } else if (Nxt == 'l') {
          talk_Set(talk_Formant(580, 1799, 2605, 3677), 0, 100, 100, 100);
          talk_Set(talk_Formant(310, 1050, 2880, 3500), 0, 100, 200, 50);
        } else if (1) {
          (Ptr--);
          talk_Set(talk_Formant(580, 1799, 2605, 3677), 0, 100, 100, 100);
        }
      } else if (This == 'i') {
        if (Nxt == 'r') {
          talk_Set(talk_Formant(470, 1120, 2430, 3400), 0, 100, 200, 100);
          talk_Set(talk_Formant(310, 1060, 1380, 3500), (int32_t)"\022", 100, 200, 200);
        } else if (1) {
          (Ptr--);
          talk_Set(talk_Formant(400, 2000, 2550, 3900), 0, 100, 150, 100);
        }
      } else if (This == 'o') {
        if (Nxt == 'a') {
          talk_Set(talk_Formant(640, 1200, 2400, 3000), 0, 100, 0, 150);
          talk_Set(talk_Formant(300, 870, 2250, 3900), 0, 150, 100, 100);
        } else if (Nxt == 'r') {
          talk_Set(talk_Formant(640, 1200, 2400, 3000), 0, 100, 0, 100);
          talk_Set(talk_Formant(300, 870, 2250, 3900), 0, 100, 0, 100);
          talk_Set(talk_Formant(470, 1120, 2430, 3400), (int32_t)"\016\024", 100, 0, 50);
          talk_Set(talk_Formant(310, 1060, 1380, 3500), (int32_t)"\022", 50, 200, 200);
        } else if (Nxt == 'l') {
          talk_Set(talk_Formant(650, 990, 2530, 3480), 0, 200, 200, 100);
          talk_Set(talk_Formant(310, 1050, 2880, 3500), 0, 100, 200, 50);
        } else if (Nxt == 'u' || Nxt == 'w') {
          talk_Set(talk_Formant(660, 1700, 2400, 3900), 0, 100, 100, 300);
          talk_Set(talk_Formant(300, 870, 2250, 3900), 0, 300, 50, 100);
        } else if (Nxt == 'i' || Nxt == 'y') {
          talk_Set(talk_Formant(640, 1200, 2400, 3000), 0, 100, 0, 150);
          talk_Set(talk_Formant(300, 870, 2250, 3900), 0, 150, 0, 200);
          talk_Set(talk_Formant(310, 2020, 2960, 3500), 0, 200, 50, 100);
        } else if (Nxt == 'o') {
          talk_Set(talk_Formant(300, 870, 2250, 3900), 0, 100, 200, 100);
        } else if (1) {
          (Ptr--);
          talk_Set(talk_Formant(650, 990, 2530, 3480), 0, 200, 200, 100);
        }
      } else if (This == 'u') {
        if (Nxt == 'u') {
          talk_Set(talk_Formant(470, 1120, 2430, 3400), 0, 100, 200, 100);
        } else if (1) {
          (Ptr--);
          talk_Set(talk_Formant(640, 1200, 2400, 3000), 0, 100, 200, 100);
        }
      } else if (This == 'd') {
        if (Nxt == 'h') {
          talk_Set(0, (int32_t)"\022", 0, 30, 0);
          talk_Set(talk_Formant(350, 1800, 2820, 3400), (int32_t)"\022\016\005\020\005\014\372", 0, 100, 0);
        } else if (1) {
          (Ptr--);
          talk_Set(talk_Formant(400, 1600, 2600, 3500), (int32_t)"\022", 0, 100, 0);
          talk_Set(0, (int32_t)"\r\310", 0, 10, 10);
          talk_Set(0, (int32_t)"\r\024\0172\n\024", 100, 100, 100);
        }
      } else if (This == 't') {
        if (Nxt == 'h') {
          talk_Set(0, (int32_t)"\022", 0, 30, 0);
          talk_Set(talk_Formant(350, 1800, 2820, 3400), (int32_t)"\022\020\n\014\372", 0, 200, 50);
        } else if (1) {
          (Ptr--);
          talk_Set(talk_Formant(400, 1600, 2600, 3500), (int32_t)"\022", 0, 100, 0);
          talk_Set(0, (int32_t)"\022\r\310", 0, 10, 10);
          talk_Set(0, (int32_t)"\022\r\024\0172\n\024", 100, 100, 100);
        }
      } else if (This == 's') {
        if (Nxt == 'h') {
          talk_Set(0, (int32_t)"\022", 0, 30, 0);
          talk_Set(talk_Formant(470, 1120, 2430, 3400), (int32_t)"\022\r\n\020\005\0142", 0, 200, 0);
          talk_Set(0, (int32_t)"\022", 0, 1, 50);
        } else if (1) {
          (Ptr--);
          talk_Set(0, (int32_t)"\022", 0, 30, 0);
          talk_Set(talk_Formant(19, 38, 57, 57), (int32_t)"\022\020\002\014d", 0, 200, 0);
          talk_Set(talk_Formant(470, 1120, 2430, 3400), (int32_t)"\016\377", 0, 1, 50);
        }
      } else if (This == 'c' || This == 'k') {
        if ((This == 'c') && (Nxt == 'h')) {
          talk_Set(0, (int32_t)"\022", 0, 30, 0);
          talk_Set(talk_Formant(260, 2070, 3020, 3500), (int32_t)"\022\014d\020\005", 0, 100, 200);
          talk_Set(0, (int32_t)"\016\377", 0, 1, 50);
        } else {
          (Ptr--);
          if (Nxt == 'a' || Nxt == 'e' || Nxt == 'i' || Nxt == 'o' || Nxt == 'u') {
            thisobj.Initial_k = -1;
          } else if (1) {
            talk_Set(talk_Formant(50, 1750, 1750, 3500), (int32_t)"\022", 50, 1, 1);
            talk_Set(0, (int32_t)"\022", 10, 1, 1);
            talk_Set(0, (int32_t)"\022\020\036\014Z", 0, 15, 0);
            talk_Set(0, (int32_t)"\022", 0, 40, 0);
          }
        }
      } else if (This == 'g') {
        (Ptr--);
        if (Nxt == 'a' || Nxt == 'e' || Nxt == 'i' || Nxt == 'o' || Nxt == 'u') {
          thisobj.Initial_g = -1;
        } else if (1) {
          talk_Set(talk_Formant(300, 1990, 2850, 3500), (int32_t)"\022\016\024\r\310", 0, 10, 10);
          talk_Set(0, (int32_t)"\022\016\024\r\024\0172\n\024", 40, 40, 10);
        }
      } else if (This == 'z') {
        if (Nxt == 'h') {
          talk_Set(talk_Formant(470, 1120, 2430, 3400), (int32_t)"\022\016\024\r\n\020\005\0142", 50, 300, 0);
        } else if (1) {
          (Ptr--);
          talk_Set(talk_Formant(150, 1400, 2300, 3180), (int32_t)"\014\372\020\n\016\024", 200, 100, 200);
        }
      } else if (This == 'r') {
        if (Nxt == 'r') {
          {
            int32_t _idx__0000;
            for(_idx__0000 = 1; _idx__0000 <= 3; (_idx__0000 = (_idx__0000 + 1))) {
              talk_Set(talk_Formant(310, 1060, 1380, 3500), (int32_t)"\022", 0, 50, 200);
              talk_Set(talk_Formant(640, 1200, 2400, 3000), (int32_t)"\016\017", 10, 15, 10);
            }
          }
        } else if (1) {
          (Ptr--);
        }
        talk_Set(talk_Formant(310, 1060, 1380, 3500), (int32_t)"\022", 0, 50, 200);
      }
    } else if (1) {
      if (This == 'l') {
        talk_Set(talk_Formant(310, 1050, 2880, 3500), 0, 0, 200, 50);
      } else if (This == 'w') {
        talk_Set(talk_Formant(290, 610, 2150, 3500), (int32_t)"\022", 0, 50, 200);
      } else if (This == 'y') {
        talk_Set(talk_Formant(310, 2020, 2960, 3500), (int32_t)"\022", 0, 100, 200);
      } else if (This == 'm') {
        talk_Set(talk_Formant(480, 1270, 2130, 3500), (int32_t)"\022\016\005\017\005\n\016", 10, 200, 30);
      } else if (This == 'n') {
        talk_Set(talk_Formant(480, 1340, 2470, 3500), (int32_t)"\022\016\005\017\005\n\016", 10, 200, 30);
      } else if (This == 'p') {
        talk_Set(talk_Formant(400, 1100, 2150, 3500), (int32_t)"\022", 0, 100, 0);
        talk_Set(0, (int32_t)"\022\r<", 0, 10, 10);
        talk_Set(0, (int32_t)"\022\r\024\0172\n\024", 100, 100, 100);
      } else if (This == 'b') {
        talk_Set(talk_Formant(200, 1100, 2150, 3500), (int32_t)"\022", 0, 100, 10);
        talk_Set(0, (int32_t)"\022\016\n", 10, 40, 10);
      } else if (This == 'f') {
        talk_Set(0, (int32_t)"\022", 0, 30, 0);
        talk_Set(talk_Formant(19, 38, 57, 57), (int32_t)"\022\020\002\014\372", 0, 200, 0);
        talk_Set(talk_Formant(470, 1120, 2430, 3400), (int32_t)"\016\377", 0, 1, 50);
      } else if (This == 'h') {
        thisobj.Aspirate = -1;
      } else if (This == 'v') {
        talk_Set(talk_Formant(220, 1100, 2080, 3500), (int32_t)"\022\014\372\020\002", 0, 100, 200);
      } else if (This == 'j') {
        talk_Set(talk_Formant(260, 2070, 3020, 3500), (int32_t)"\022\016\n\014d\020\n", 0, 150, 100);
      }
    }
  }
  talk_Set(0, (int32_t)"\022", 0, 1, 0);
  return result;
}

int32_t talk_Formant(int32_t Sf1, int32_t Sf2, int32_t Sf3, int32_t Sf4)
{
  if (Sf1) {
    thisobj.Vt[F1] = (Sf1 / 19);
  }
  if (Sf2) {
    thisobj.Vt[F2] = (Sf2 / 19);
  }
  if (Sf3) {
    thisobj.Vt[F3] = (Sf3 / 19);
  }
  if (Sf4) {
    thisobj.Vt[F4] = (Sf4 / 19);
  }
  return 0;
}

int32_t talk_Set(int32_t Fmt, int32_t Ptr, int32_t Pre, int32_t Time, int32_t Post)
{
  int32_t	This, Nxt, Vol;
  if (Ptr) {
    while ((This = ((uint8_t *)(Ptr++))[0])) {
      if (This == Zero) {
        This = 0;
      }
      if (This == Qt) {
        thisobj.Vt[Aa] = (thisobj.Vt[Ga] = (thisobj.Vt[Na] = (thisobj.Vt[Fa] = 0)));
      } else {
        if ((Nxt = ((uint8_t *)(Ptr++))[0])) {
          if (Nxt == Zero) {
            Nxt = 0;
          }
          thisobj.Vt[This] = Nxt;
        } else {
          if (!abortChain__) abort();
          abortChain__->val =  0;
          longjmp(abortChain__->jmp, 1);
        }
      }
    }
  }
  if ((Pre) || (Time)) {
    if (thisobj.Aspirate) {
      thisobj.Vt[Aaz] = (thisobj.Vt[Gaz] = 0);
      VocalTract_Go(1);
      thisobj.Vt[Aaz] = 10;
      VocalTract_Go((Max__(((200 * thisobj.Dilate) / 100), 1)));
      thisobj.Glide = 0;
      thisobj.Aspirate = 0;
    } else {
      if ((thisobj.Initial_k) || (thisobj.Initial_g)) {
        memcpy( (void *)&thisobj.Vtp, (void *)&thisobj.Vt, 1*(18));
        if (thisobj.Initial_g) {
          thisobj.Vt[F1] = (Shr__(thisobj.Vtp[F1], 2));
          thisobj.Vt[F2] = (thisobj.Vt[F3] = (Shr__((thisobj.Vtp[F2] + thisobj.Vtp[F3]), 1)));
        } else {
          thisobj.Vt[F1] = (Shr__((thisobj.Vt[F1] * 3), 2));
          thisobj.Vt[F2] = (Shr__(((thisobj.Vtp[F2] * 3) + thisobj.Vtp[F3]), 2));
          thisobj.Vt[F3] = (Shr__(((thisobj.Vtp[F3] * 3) + thisobj.Vtp[F2]), 2));
        }
        thisobj.Initial_k = 0;
        thisobj.Initial_g = 0;
        talk_Set(0, (int32_t)"\022", 10, 1, 1);
        talk_Set(0, (int32_t)"\022\020\036\014Z", 0, 15, 0);
        talk_Set(0, (int32_t)"\022", 0, 40, 0);
        talk_Set(0, (int32_t)"\016\002", 0, 10, 100);
        memcpy( (void *)&thisobj.Vt, (void *)&thisobj.Vtp, 1*(18));
      }
    }
    if (thisobj.Whisper) {
      thisobj.Vt[Aa] = (Max__(thisobj.Vt[Aa], thisobj.Vt[Ga]));
      thisobj.Vt[Ga] = 0;
    }
    Vol = ((uint8_t *)(int32_t)" %,3;EP^m\200")[thisobj.Volume];
    thisobj.Vt[Gaz] = (Shr__((thisobj.Vt[Ga] * Vol), 7));
    thisobj.Vt[Aaz] = (Shr__((thisobj.Vt[Aa] * Vol), 7));
    thisobj.Vt[Faz] = (Shr__((thisobj.Vt[Fa] * Vol), 7));
    thisobj.Vt[Naz] = (Shr__((thisobj.Vt[Na] * Vol), 7));
    VocalTract_Go((Max__((((Min__(Pre, thisobj.Glide)) * thisobj.Dilate) / 100), 1)));
    thisobj.Vt[Gp] = thisobj.Vt[Gps];
    VocalTract_Go((Max__(((Time * thisobj.Dilate) / 100), 1)));
  }
  thisobj.Glide = Post;
  thisobj.Vt[Fa] = 0;
  thisobj.Vt[Ga] = 40;
  return 0;
}

