//
// automatically generated by spin2cpp v1.03 on Wed Sep 04 18:41:35 2013
// ..\spin2cpp.exe --ccode talk.spin 
//

#ifndef VocalTract_Class_Defined__
#define VocalTract_Class_Defined__

#include <stdint.h>

#define Frame_buffers (8)
#define Frame_bytes (16)
#define Frame_longs (4)
#define Frame_buffer_bytes (128)
#define Frame_buffer_longs (32)

typedef struct VocalTract {
  int32_t	Cog, Tract, Pace;
  int32_t	Index, Attenuation, Sample;
  int32_t	Dira_, Dirb_, Ctra_, Ctrb_, Frqa_, Cnt_;
  int32_t	Frames[32];
  char dummy__;
} VocalTract;

  int32_t	VocalTract_Start(int32_t Tract_ptr, int32_t Pos_pin, int32_t Neg_pin, int32_t Fm_offset);
  int32_t	VocalTract_Stop(void);
  int32_t	VocalTract_Set_attenuation(int32_t Level);
  int32_t	VocalTract_Set_pace(int32_t Percentage);
  int32_t	VocalTract_Go(int32_t Time);
  int32_t	VocalTract_Full(void);
  int32_t	VocalTract_Empty(void);
  int32_t	VocalTract_Sample_ptr(void);
  int32_t	VocalTract_Aural_id(void);
#endif
